version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build: .
    depends_on:
      - rabbitmq
    restart: on-failure
    env_file: 
      - .env