version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo:3.6.18
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  worker:
    image: codingblocks/certificate-worker
    build: .
    ports: 
      - "4242:80"
    depends_on:
      - rabbitmq
      - mongo
    restart: on-failure
    env_file: 
      - .env